# Generated by Django 4.1.5 on 2023-07-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_games_developers'),
        ('wishlist', '0002_alter_wishlist_game_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='game_list',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='game_list',
            field=models.ManyToManyField(related_name='items', to='content.games'),
        ),
    ]
