# Generated by Django 4.1.5 on 2023-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='developers',
        ),
        migrations.AddField(
            model_name='games',
            name='developers',
            field=models.ManyToManyField(related_name='Developers', to='content.developer'),
        ),
    ]
